AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Task Manager API

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs20.x
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Parameters:
  TableName:
    Type: String
    Default: TaskTable

Resources:
  TaskTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Ref: TableName
      AttributeDefinitions: 
        - AttributeName: taskId
          AttributeType: S
      KeySchema: 
        - AttributeName: taskId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST 

  CreateTaskFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: createTask.handler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: TableName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /task/create
            Method: POST

  GetTaskListFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: getTaskList.handler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TableName
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              Ref: TableName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /task/list
            Method: GET
  
  UpdateTaskFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: updateTask.handler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: TableName     
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /task/update/{taskId}
            Method: PATCH
  
  DeleteTaskFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: deleteTask.handler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Environment:
        Variables:
          TABLE_NAME:
            Ref: TableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: TableName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /task/delete/{taskId}
            Method: DELETE
